Ngo index 2
dumboluzz/shipment-tracker pull request #18
Opened 2022-06-03 14:50 UTC by sophiecs333

- added buttons according to shipment status
- made partial for shipment card

2022-06-05 18:51 UTC, dumboluzz requested changes

2022-06-05 18:51 UTC, dumboluzz commented on app/assets/stylesheets/pages/_admin-index.scss
> +$light-red: #FFCCD5;
maybe we should change the bootstrap success and danger colors as well

2022-06-05 18:51 UTC, dumboluzz commented on app/assets/stylesheets/pages/_admin-index.scss
> +}
you can also use the bootstrap class fw-bold

2022-06-05 18:51 UTC, dumboluzz commented on app/models/shipment.rb
> +      donors.first
if there are no pallets aka. no donors this will fail

2022-06-05 18:51 UTC, dumboluzz commented on app/views/shipments/_admin_index.html.erb
> +            <h5 class="btn-tabs" data-shipment="problematic" data-action="click->update-shipments#update">Problem</h5>
These should propably be buttons. The active button should change depending on the query.

2022-06-05 18:51 UTC, dumboluzz commented on app/views/shipments/_admin_index.html.erb
> +            # event on click? and then if/else
This shows up in on the webpage.

2022-06-05 18:51 UTC, dumboluzz commented on app/views/shipments/_shipment_card_admin_index.html.erb
> +          <p>Last scan</p> <p> | </p> <p><%= shipment.scans.last.date.strftime("%a %e %b,  %l:%M  %p") %></p>
This will fail if the shipment has no last scan.

2022-06-06 08:02 UTC, sophiecs333 commented on app/assets/stylesheets/pages/_admin-index.scss
> +$light-red: #FFCCD5;
Ok I added them.

2022-06-06 08:16 UTC, sophiecs333 commented on app/models/shipment.rb
> +      donors.first
Would this work?

if donors.uniq.size < 2
  donors.first
elsif donors.size < 1
  ""
else
  donors.uniq.join(", ")[0..20] + "..."
end

2022-06-06 10:57 UTC, sophiecs333 commented
I made some changes related to the comments above.
Now we will need to have a look at the divs / bootstrap positioning, I think they can be improved.

2022-06-06 13:33 UTC, dumboluzz commented on app/models/shipment.rb
> +      ""
This will never execute. If size < 1 then uniq.size is also < 2.

2022-06-06 13:33 UTC, dumboluzz commented on app/assets/stylesheets/pages/_admin-index.scss
> +  color: $dark-grey;
This changes the font color of the entire app. Is this intented? We would have to add the dark text color to everything that we dont want to be grey

2022-06-06 13:56 UTC, sophiecs333 commented on app/assets/stylesheets/pages/_admin-index.scss
> +  color: $dark-grey;
Changed!

2022-06-06 14:05 UTC, dumboluzz approved these changes

2022-06-06 14:24 UTC, merged